#pragma once

#define CHUNK_SIZE 16
#define CHUNK_HEIGHT 256
#define RENDER_DISTANCE 10
#define CONTINENTAL_SCALE 15.f
#define TEMPERATURE_SCALE 8.f
#define EROSION_SCALE 10.f
#define PEAKS_VALLEYS_SCALE 5.f
#define CAVE_SCALE 3.f

#define SEA_LEVEL 57